name: Lint with awesome-lint

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Run awesome linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g awesome-lint
    - run: awesome-lint README.md
